### PR TITLE
feat: Support `encryption_configuration` for `aws_sfn_state_machine`

### PR DESCRIPTION
**Pull request by magreenbaum**
## Description
Support `encryption_configuration` for `aws_sfn_state_machine`.

## Motivation and Context
https://github.com/hashicorp/terraform-provider-aws/pull/38574
https://docs.aws.amazon.com/step-functions/latest/dg/encryption-at-rest.html

## Breaking Changes
No.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Review by bryantbiggs — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 4.2.1 :tada:

**Comment by guillaumelecerf** [comment]
@antonbabenko: this must have been a major version bump, as the required terraform provider went from >= 5.6 to >= 5.61 (in https://github.com/terraform-aws-modules/terraform-aws-step-functions/pull/66)

**Comment by antonbabenko** [comment]
@guillaumelecerf You are right, but this PR was merged with an incorrect commit message. It should have followed the `conventional commits` pattern to trigger a minor release (`feat: ...` - correct commit message).

**Comment by guillaumelecerf** [comment]
> @guillaumelecerf You are right, but this PR was merged with an incorrect commit message. It should have followed the `conventional commits` pattern to trigger a minor release (`feat: ...` - correct commit message).

Would be nice that this could be enforced by a check, as it is done for the PR title

**Pull request merged**
