### PR TITLE
fix: Add default resource to ECS and Batch Events, IAM PassRole

### PR DESCRIPTION
**Pull request by thomas-maschler**
## Description

Add default resource for ECS and Batch events. With out these resources usage of ECS and Batch service causes
`Error: AccessDeniedException: 'arn:aws:iam::xxxx:role/step-functions-role' is not authorized to create managed-rule.`

## Motivation and Context

#11 

## How Has This Been Tested?
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

Deployed module in own project with

```terraform
 batch_Sync = {
      batch = ["*"]
      events = true
    }

    iam_PassRole = {
      iam = ["*"]
    }
```

This allowed me to successfully deploy my step function with Batch Integration.
It also create a  Iam:PassRole policy and attached it to the service role.

```
# module.step_function.aws_iam_policy.service["iam_PassRole"] will be created
  + resource "aws_iam_policy" "service" {
      + arn       = (known after apply)
      + id        = (known after apply)
      + name      = "project-step_function-test-batch-iam_PassRole"
      + path      = "/"
      + policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = "iam:PassRole"
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "iamPassRoleIam"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id = (known after apply)
      + tags_all  = (known after apply)
    }

# module.step_function.aws_iam_policy_attachment.service["iam_PassRole"] will be created
  + resource "aws_iam_policy_attachment" "service" {
      + id         = (known after apply)
      + name       = "project-step_function-test-batch-iam_PassRole"
      + policy_arn = (known after apply)
      + roles      = [
          + "project-step_function-test-batch",
        ]
    }
```

### CODE REVIEW

**Comment by antonbabenko** [comment]
Hi @thomas-maschler !

Thanks for this PR but I don't think we need this because `default_resources` defined in locals really default and they don't contain any specific assumptions (like region or account_id). They are usually `*` or `arn:...*`.

In your case you will have to specify them like this:

```hcl
batch_Sync = {
   batch = ["*"]
   events = ["arn:aws:events:${local.aws_region}:${data.aws_caller_identity.current.account_id}:rule/StepFunctionsGetEventsForBatchJobsRule"]
}

iam_PassRole = {
   iam = ["*"]
}
```

Please remove your changes related to `ecs_Sync` and `batch_Sync`, but keep `iam_PassRole` added. I think it is good to have it listed there in `locals`.

**Comment by thomas-maschler** [comment]
Thanks @antonbabenko, I removed those edits. 

However, I think there should be a place somewhere, (maybe even as an example or in the documentation) where you indicate that those values are required. Any user who want to use this module with ECS or Batch integration will need to add them in order to successfully run TF apply.

If you don't want to make any assumption you could even use `arn:aws:events:*:*:rule/StepFunctionsGetEventsForBatchJobsRule`
or `arn:aws:events:*:*:rule/*`

**Comment by antonbabenko** [comment]
Great! If you can, please update README and include info describing what should be implemented (as you say) to be able to use this module with ECS or Batch, and link to the chapter in the official documentation by AWS (it helps everyone to understand the whole picture and in the future doing code reviews).

Opening IAM role to wider ARNs like `*:rule/StepFunctionsGetEventsForBatchJobsRule` or `*:rule/*` is rather risky unless AWS forces us to do so. We should let users do a judged decision on this and don't hide it in the module.

**Comment by antonbabenko** [comment]
Fixed in #24 

[v2.5.0](https://github.com/terraform-aws-modules/terraform-aws-step-function/releases/v2.5.0) has been just released.

**Pull request closed without merging**
